---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(RMySQL)
library(tidyverse)
library(shinydashboard)
library(dashboardthemes)
library(ggplot2)
library(readxl)
```

# load description
```{r}
LCDataDictionary <- read_excel("data/LCDataDictionary.xlsx", 
    sheet = "LoanStats")
```

# table df
```{r}
table_name <- c("loan","borrower","bankcard","bank_accounts","inquries","installment","raw")
loan <- c("id", "int_rate", "grade","loan_amnt","loan_status","disbursement_method","title","zip_code","funded_amnt","funded_amnt_inv","initial_list_status","purpose")
borrower <- c("id","addr_state","annual_inc","verification_status","home_ownership","last_credit_pull_d","emp_title","emp_length","total_acc","delinq_2yrs","open_acc","delinq_amnt","earliest_cr_line","pub_rec_bankruptcies","pub_rec")
bankcard <- c("id","mths_since_recent_bc","num_actv_bc_tl","num_bc_sats","num_bc_tl","total_bc_limit")
bank_accounts <- c("id","mo_sin_rcnt_tl","num_accts_ever_120_pd","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","tot_cur_bal")
inquries <- c("id","inq_fi","inq_last_12m","mths_since_recent_inq")
installment <- c("id","installment","mo_sin_old_il_acct","mths_since_rcnt_il","num_il_tl")
raw <- c("id", "int_rate", "grade","loan_amnt","loan_status","disbursement_method","title","zip_code","funded_amnt","funded_amnt_inv","initial_list_status","purpose","addr_state","annual_inc","verification_status","home_ownership","last_credit_pull_d","emp_title","emp_length","total_acc","delinq_2yrs","open_acc","delinq_amnt","earliest_cr_line","pub_rec_bankruptcies","pub_rec","mths_since_recent_bc","num_actv_bc_tl","num_bc_sats","num_bc_tl","total_bc_limit","mo_sin_rcnt_tl","num_accts_ever_120_pd","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","tot_cur_bal","inq_fi","inq_last_12m","mths_since_recent_inq","installment","mo_sin_old_il_acct","mths_since_rcnt_il","num_il_tl")

table_df <- as.data.frame(matrix(data = NA, nrow = 46,ncol = 7))
names(table_df) <- table_name
table_df$loan[1:length(loan)] <- loan
table_df$borrower[1:length(borrower)] <- borrower
table_df$bankcard[1:length(bankcard)] <- bankcard
table_df$bank_accounts[1:length(bank_accounts)] <- bank_accounts
table_df$inquries[1:length(inquries)] <- inquries
table_df$installment[1:length(installment)] <- installment
table_df$raw[1:length(raw)] <- raw
```

# theme
```{r}
### creating custom theme object
theme_loan <- shinyDashboardThemeDIY(
  
    ### general
    appFontFamily = "Arial"
    ,appFontColor = "rgb(0,0,0)"
    ,primaryFontColor = "rgb(0,0,0)"
    ,infoFontColor = "rgb(0,0,0)"
    ,successFontColor = "rgb(0,0,0)"
    ,warningFontColor = "rgb(0,0,0)"
    ,dangerFontColor = "rgb(0,0,0)"
    ,bodyBackColor = "rgb(248,248,248)"
  
    ### header
    ,logoBackColor = "rgb(18,95,160)"
  
    ,headerButtonBackColor = "rgb(238,238,238)"
    ,headerButtonIconColor = "rgb(75,75,75)"
    ,headerButtonBackColorHover = "rgb(210,210,210)"
    ,headerButtonIconColorHover = "rgb(0,0,0)"
  
    ,headerBackColor = "rgb(238,238,238)"
    ,headerBoxShadowColor = "#aaaaaa"
    ,headerBoxShadowSize = "2px 2px 2px"
  
    ### sidebar
    ,sidebarBackColor = cssGradientThreeColors(
      direction = "down"
      ,colorStart = "rgb(118,158,207)"
      ,colorMiddle = "rgb(118,158,207)"
      ,colorEnd = "rgb(118,158,207)"
      ,colorStartPos = 0
      ,colorMiddlePos = 50
      ,colorEndPos = 100
    )
    ,sidebarPadding = 0
  
    ,sidebarMenuBackColor = "transparent"
    ,sidebarMenuPadding = 0
    ,sidebarMenuBorderRadius = 0
  
    ,sidebarShadowRadius = "3px 5px 5px"
    ,sidebarShadowColor = "#aaaaaa"
  
    ,sidebarUserTextColor = "rgb(255,255,255)"
  
    ,sidebarSearchBackColor = "rgb(55,72,80)"
    ,sidebarSearchIconColor = "rgb(153,153,153)"
    ,sidebarSearchBorderColor = "rgb(55,72,80)"
  
    ,sidebarTabTextColor = "rgb(255,255,255)"
    ,sidebarTabTextSize = 13
    ,sidebarTabBorderStyle = "none none solid none"
    ,sidebarTabBorderColor = "rgb(35,106,135)"
    ,sidebarTabBorderWidth = 1
  
    ,sidebarTabBackColorSelected = cssGradientThreeColors(
      direction = "right"
      ,colorStart = "rgb(18,95,160)"
      ,colorMiddle = "rgb(18,95,160)"
      ,colorEnd = "rgb(18,95,160)"
      ,colorStartPos = 0
      ,colorMiddlePos = 30
      ,colorEndPos = 100
    )
    ,sidebarTabTextColorSelected = "rgb(255,255,255)"
    ,sidebarTabRadiusSelected = "5px 5px 5px 5px"
  
    ,sidebarTabBackColorHover = cssGradientThreeColors(
      direction = "right"
      ,colorStart = "rgb(18,95,160)"
      ,colorMiddle = "rgb(18,95,160)"
      ,colorEnd = "rgb(18,95,160)"
      ,colorStartPos = 0
      ,colorMiddlePos = 30
      ,colorEndPos = 100
    )
    ,sidebarTabTextColorHover = "rgb(255,255,255)"
    ,sidebarTabBorderStyleHover = "none none solid none"
    ,sidebarTabBorderColorHover = "rgb(75,126,151)"
    ,sidebarTabBorderWidthHover = 1
    ,sidebarTabRadiusHover = "5px 5px 5px 5px"
  
    ### boxes
    ,boxBackColor = "rgb(255,255,255)"
    ,boxBorderRadius = 5
    ,boxShadowSize = "0px 1px 1px"
    ,boxShadowColor = "rgba(0,0,0,.1)"
    ,boxTitleSize = 16
    ,boxDefaultColor = "rgb(210,214,220)"
    ,boxPrimaryColor = "rgba(44,222,235,1)"
    ,boxInfoColor = "rgb(210,214,220)"
    ,boxSuccessColor = "rgba(0,255,213,1)"
    ,boxWarningColor = "rgb(244,156,104)"
    ,boxDangerColor = "rgb(255,88,55)"
  
    ,tabBoxTabColor = "rgb(255,255,255)"
    ,tabBoxTabTextSize = 14
    ,tabBoxTabTextColor = "rgb(0,0,0)"
    ,tabBoxTabTextColorSelected = "rgb(0,0,0)"
    ,tabBoxBackColor = "rgb(255,255,255)"
    ,tabBoxHighlightColor = "rgb(18,95,160)"
    ,tabBoxBorderRadius = 5
  
    ### inputs
    ,buttonBackColor = "rgb(245,245,245)"
    ,buttonTextColor = "rgb(0,0,0)"
    ,buttonBorderColor = "rgb(200,200,200)"
    ,buttonBorderRadius = 5
  
    ,buttonBackColorHover = "rgb(235,235,235)"
    ,buttonTextColorHover = "rgb(100,100,100)"
    ,buttonBorderColorHover = "rgb(200,200,200)"
  
    ,textboxBackColor = "rgb(255,255,255)"
    ,textboxBorderColor = "rgb(200,200,200)"
    ,textboxBorderRadius = 5
    ,textboxBackColorSelect = "rgb(245,245,245)"
    ,textboxBorderColorSelect = "rgb(200,200,200)"
  
    ### tables
    ,tableBackColor = "rgb(255,255,255)"
    ,tableBorderColor = "rgb(240,240,240)"
    ,tableBorderTopSize = 1
    ,tableBorderRowSize = 1
  
  )
```



```{r}
## app.R ##

header <- dashboardHeader(title = "Loan Dashboard", titleWidth = 300)

sidebar <- dashboardSidebar(
  width = 300,
  sidebarMenuOutput("sidebar")
)



body <- dashboardBody(
  
  tabItems(
    # origin table
    tabItem(tabName = "origin_table",
            h2("Original Table"),
            fluidRow(
              # row number control
              box(solidHeader = TRUE,
                  collapsible = TRUE,
                  width = 12,
                  title = "Observation number",
                  sliderInput(inputId = "row_num", 
                              label = "Choose observation number:", 
                              min = 1, max = 1000, value = 20)
                  ),
              #table output
              box(
                  width = 12,
                  tableOutput("select_table"),
                  solidHeader = TRUE,
                  collapsible = TRUE)
            )
            ),
    
    # data histogram
    tabItem(tabName = "one_col",
            h2("Attribute Description"),
            # Boxes need to be put in a row (or column)
            fluidRow(
              #select solumn
              box(uiOutput("column_select"),
                  sliderInput(inputId = "row_num2", 
                              label = "Choose observation number:", 
                              min = 1, max = 1000000, value = 20)),
              box(title = "Attribute Introduction:",
                  textOutput("col_description"),
                  #"There is an introduction about the attribute selected for visualization, which we do not have the information yet.",
                  solidHeader = TRUE,
                  collapsible = TRUE)
            ),
            
            # show histogram
            fluidRow(
              box(title = "Histogram",
                  width = 12,
                  plotOutput("col_plot"))
              )
            
            ),
    
    # update
    tabItem(tabName = "update",
            h2("Operation - Update"),
            fluidRow(
              # update inputs
              box(uiOutput("update_where_column"),
                  uiOutput("update_where_value"),
                  uiOutput("update_column"),
                  uiOutput("update_to_be"),
                  actionButton(inputId = "click_update",label = "Confirm Update",width = 200),
                  textOutput("update_result")
                  )
            ),
            fluidRow(
              # show updated table
              box(title = "Update result",
                  width = 12,
                  tableOutput("update_table"),
                  solidHeader = TRUE,
                  collapsible = TRUE)
            )
    ),
    
    # insert
    tabItem(tabName = "insert",
            h2("Operation - Insert"),
            fluidRow(
              #show the target table
              box(title = "Target table",
                  width = 12,
                  tableOutput("insert_table_before"),
                  solidHeader = TRUE,
                  collapsible = TRUE)
            ),
            fluidRow(
              # inputs
              box(uiOutput("insert_values"),
                  actionButton(inputId = "click_insert",label = "Confirm Insert",width = 200),
                  textOutput("insert_result"),
                  width = 12)
            ),
            fluidRow(
              # show the table after insert
              box(title = "Insert result",
                  width = 12,
                  tableOutput("insert_table"),
                  solidHeader = TRUE,
                  collapsible = TRUE)
            )
    ),
    
    # delete
    tabItem(tabName = "delete",
            h2("Operation - Delete"),
            fluidRow(
              box(uiOutput("delete_where_column"),
                  uiOutput("delete_where_value"),
                  textOutput("test"),#######
                  actionButton(inputId = "click_delete",label = "Cofirm Delete",width = 200),
                  textOutput("delete_result"))
            )
      
    )
    
    


  )
)
```



```{r}
ui <- dashboardPage(header, sidebar, body,
                    theme_loan)

server <- function(input, output) {
  
  # Sidebar ui
  output$sidebar <- renderMenu({
    sidebarMenu(
      selectInput(inputId = "table", 
                  label = "Choose table:", 
                  choices = table_name, 
                  #selected = "loan", 
                  multiple = FALSE),
      menuItem("Original Table", tabName = "origin_table", icon = icon("dashboard")),
      menuItem("Attribute description", tabName = "one_col", icon = icon("dashboard")),
      menuItem("Operation", tabName = "update", icon = icon("dashboard"),
               menuSubItem("Update", tabName = "update"),
               menuSubItem("Insert", tabName = "insert"),
               menuSubItem("Delete", tabName = "delete")),
      menuItem("Download Data", icon = icon("download"), 
               href = "https://www.kaggle.com/wendykan/lending-club-loan-data")

    )
  })
  
  
  # origin_table
  output$select_table <- renderTable({
    table <- input$table
    column <- input$column
    row_num <- input$row_num
    
    sql_sentence <- paste0("SELECT * FROM ",table," LIMIT ",row_num,";")
    
    conn <- dbConnect(MySQL(), 
                  dbname = "loan", 
                  username="root", 
                  password="root",
                  host='127.0.0.1',
                  port = 3306,
                  client.flag=CLIENT_MULTI_STATEMENTS)
    data <- dbGetQuery(conn, sql_sentence)
    dbDisconnect(conn)
    
    data
  })
  
  # one_col
  output$column_select <- renderUI({
    selectInput(inputId = "column",
                label = "Choose attribute:",
                choices = na.omit(table_df[input$table]),
                selected = "id", 
                multiple = FALSE)
  })
  
  output$col_description <- renderText({
    column <- input$column
    filter(LCDataDictionary, LoanStatNew == column)[['Description']]
  })
  
  output$col_plot <- renderPlot({
    table <- input$table
    column <- input$column
    row_num <- input$row_num2
    
    sql_sentence <- paste0("SELECT * FROM ",table," LIMIT ",row_num,";")
    
    conn <- dbConnect(MySQL(), 
                  dbname = "loan", 
                  username="root", 
                  password="root",
                  host='127.0.0.1',
                  port = 3306,
                  client.flag=CLIENT_MULTI_STATEMENTS)
    data <- dbGetQuery(conn, sql_sentence)
    dbDisconnect(conn)
    
    data %>% 
      ggplot()+
      geom_bar(aes(!!as.symbol(column)),fill="#125FA0")+
      theme_bw()
      
  })
  
  ##############################################
  # update
  output$update_where_column <- renderUI({
    selectInput(inputId = "update_where_column",
                label = "Choose an attribute to locate:",
                choices = na.omit(table_df[input$table]),
                multiple = FALSE)
  })
  
  output$update_where_value <- renderUI({
    textInput(inputId = "update_where_value",
              value = 1,
              label = "Input the value to locate:")
  })
    
  output$update_column <- renderUI({
    selectInput(inputId = "update_column",
                label = "Choose an attribute you want to update:",
                choices = na.omit(table_df[input$table]),
                multiple = FALSE)
  })
      
  output$update_to_be <- renderUI({
    textInput(inputId = "update_to_be",
              label = "Update the value to be:")
  })
        
  observeEvent(input$click_update, {
    table <- input$table
    update_where_column <- input$update_where_column
    update_where_value <- input$update_where_value
    update_column <- input$update_column
    update_to_be <- input$update_to_be
    
    sql_sentence <- paste0("UPDATE ",table,
                           " SET ",update_column," = ",update_to_be, 
                           " WHERE ",update_where_column," = ",update_where_value,";")
    
    update_process <- try({
    
    conn <- dbConnect(MySQL(), 
                  dbname = "loan", 
                  username="root", 
                  password="root",
                  host='127.0.0.1',
                  port = 3306,
                  client.flag=CLIENT_MULTI_STATEMENTS)
    row_effected <- dbExecute(conn, sql_sentence)
    dbDisconnect(conn)
    
    }) # end try
    
    output$update_result <- renderText({
      result <- try(paste0(row_effected," row(s) has been effected."))
      if (class(update_process)=="try-error") {
        "Error: Insert failure. Please try again."
      }else{result}
      
      })
    
    output$update_table <- renderTable({
      table <- input$table
      update_where_column <- input$update_where_column
      update_where_value <- input$update_where_value


      sql_sentence <- paste0("SELECT * FROM ",table,
                             " WHERE ",update_where_column," = ",update_where_value,";")

      conn <- dbConnect(MySQL(),
                    dbname = "loan",
                    username="root",
                    password="root",
                    host='127.0.0.1',
                    port = 3306,
                    client.flag=CLIENT_MULTI_STATEMENTS)
      data <- dbGetQuery(conn, sql_sentence)
      dbDisconnect(conn)

      data
    })

  },ignoreNULL = T,ignoreInit = T)
  
  #######################################
  # insert
  output$insert_values <- renderUI({
    textInput(inputId = "insert_values",
              label = "Insert values:(please use comma to separate)")
  })

  observeEvent(input$click_insert, {
    table <- input$table
    insert_values <- input$insert_values
    
    sql_sentence <- paste0("INSERT INTO ",table," VALUES (",insert_values,") ;")
    
    insert_process <- try({
    
    conn <- dbConnect(MySQL(),
                    dbname = "loan",
                    username="root",
                    password="root",
                    host='127.0.0.1',
                    port = 3306,
                    client.flag=CLIENT_MULTI_STATEMENTS)
    row_effected <- dbExecute(conn, sql_sentence)
    dbDisconnect(conn)
    
    }) #end try
    
    
    
    output$insert_result <- renderText({
      result <- try(paste0(row_effected," row(s) has been effected."))
      if (class(insert_process)=="try-error") {
        # print(insert_process)
        "Error: Insert failure. Please try again."
      }else{result}
      })

    output$insert_table <- renderTable({
      table <- input$table

      sql_sentence <- paste0("SELECT * FROM ",table,
                             " ORDER BY id DESC LIMIT 5;")

      conn <- dbConnect(MySQL(),
                    dbname = "loan",
                    username="root",
                    password="root",
                    host='127.0.0.1',
                    port = 3306,
                    client.flag=CLIENT_MULTI_STATEMENTS)
      data <- dbGetQuery(conn, sql_sentence)
      dbDisconnect(conn)

      data
    })


  },ignoreNULL = T,ignoreInit = T)

  output$insert_table_before <- renderTable({
      table <- input$table

      sql_sentence <- paste0("SELECT * FROM ",table,
                             " ORDER BY id DESC LIMIT 1;")

      conn <- dbConnect(MySQL(),
                    dbname = "loan",
                    username="root",
                    password="root",
                    host='127.0.0.1',
                    port = 3306,
                    client.flag=CLIENT_MULTI_STATEMENTS)
      data <- dbGetQuery(conn, sql_sentence)
      dbDisconnect(conn)

      data
    })

  ##############################################
  # delete
  output$delete_where_column <- renderUI({
    selectInput(inputId = "delete_where_column",
                label = "Choose an attribute to locate:",
                choices = na.omit(table_df[input$table]),
                multiple = FALSE)
  })

  output$delete_where_value <- renderUI({
    textInput(inputId = "delete_where_value",
              label = "Input the value to locate:")
  })
  
  

  observeEvent(input$click_delete, {
    
    table <- input$table
    delete_where_column <- input$delete_where_column
    delete_where_value <- input$delete_where_value

    sql_sentence <- paste0('DELETE FROM ',table,' WHERE ',delete_where_column,' = ',delete_where_value,';')

    
    delete_process <- try({
    
    conn <- dbConnect(MySQL(),
                    dbname = "loan",
                    username="root",
                    password="root",
                    host='127.0.0.1',
                    port = 3306,
                    client.flag=CLIENT_MULTI_STATEMENTS)
    row_effected <- dbExecute(conn, sql_sentence)
    dbDisconnect(conn)
    
    }) # end try

    output$delete_result <- renderText({

      result <- try(paste0(row_effected," row(s) has been effected."))
      
      if (class(delete_process)=="try-error") {
        # print(insert_process)
        "Error: Delete failure. Please try again."
      }else{
        result
        }
      
      })


  },ignoreNULL = T,ignoreInit = T)

  
  
}
```

# run the app
```{r}
shinyApp(ui, server)
```




```{r}
table <- "loan"
update_column <- "loan_amnt"
update_to_be <- "2500"
update_where_column <- "id"
update_where_value <- "1"
sql_sentence <- paste0("UPDATE ",table," SET ",update_column," = ",update_to_be, " WHERE ",update_where_column," = ",update_where_value,";")

conn <- dbConnect(MySQL(), 
                  dbname = "loan", 
                  username="root", 
                  password="root",
                  host='127.0.0.1',
                  port = 3306,
                  client.flag=CLIENT_MULTI_STATEMENTS)
#data <-  dbGetQuery(conn, "SELECT id FROM bankcard")
#data <-  dbGetQuery(conn, "UPDATE loan SET loan_amnt = 3000 WHERE id = 1;")
#dbExecute(conn, sql_sentence)
#dbExecute(conn, "INSERT INTO inquries VALUES (2002000,1,1,1);")
dbExecute(conn, "DELETE FROM inquries WHERE id = 2002001")

dbDisconnect(conn)
```


```{r}
killDbConnections <- function () {

  all_cons <- dbListConnections(MySQL())

  print(all_cons)

  for(con in all_cons)
    +  dbDisconnect(con)

  print(paste(length(all_cons), " connections killed."))

}
killDbConnections()
```
